# Generated by Django 3.0.5 on 2020-06-23 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('ph_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='physio_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=50)),
                ('ph_no', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('image', models.ImageField(upload_to='physio/images/')),
                ('experience', models.CharField(max_length=4)),
                ('proof_image', models.ImageField(upload_to='physio/proof_images')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ans', models.CharField(max_length=30)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.area')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.city')),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.degree')),
            ],
        ),
        migrations.CreateModel(
            name='recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_title', models.CharField(max_length=30)),
                ('recruitment_photo', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='security_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='physio/treatment')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('physio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.physio_master')),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='sub_treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_treatment_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.degree')),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('video_photo', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('physio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.physio_master')),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.treatment')),
            ],
        ),
        migrations.AddField(
            model_name='physio_master',
            name='security_que_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.security_question'),
        ),
        migrations.AddField(
            model_name='physio_master',
            name='specialization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.specialization'),
        ),
        migrations.AddField(
            model_name='physio_master',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.state'),
        ),
        migrations.CreateModel(
            name='patient_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=50)),
                ('ph_no', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('image', models.ImageField(blank=True, upload_to='patient/images')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ans', models.CharField(max_length=30)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.area')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.city')),
                ('security_que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.security_question')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.patient_master')),
                ('physio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.physio_master')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.patient_master')),
                ('physio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.physio_master')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='physio_app.state'),
        ),
        migrations.AddField(
            model_name='area',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.city'),
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=10, null=True)),
                ('date_of_appointment', models.DateField(default='', max_length=10, null=True)),
                ('patient_description', models.CharField(max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default='', null=True)),
                ('note', models.CharField(default='', max_length=30, null=True)),
                ('is_active', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.patient_master')),
                ('physio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.physio_master')),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physio_app.treatment')),
            ],
        ),
    ]
